export const GOALS: any = {
    questions: [
        {
            id: 1,
            key: 'Education Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Goals'
        },
        {
            id: 2,
            key: 'Task to Reach Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Tasks'
        },
        {
            id: 3,
            key: 'Progress to Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Progress'
        },
        {
            id: 4,
            key: 'Completion Date',
            value: '',
            isRadio: false,
            isInput: false,
            isCheckbox: false,
            isDropdown: false,
            isDate: true,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Completion'
        },
        {
            id: 5,
            key: 'Housing Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Goals'
        },
        {
            id: 6,
            key: 'Task to Reach Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Tasks'
        },
        {
            id: 7,
            key: 'Progress to Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Progress'
        },
        {
            id: 8,
            key: 'Completion Date',
            value: '',
            isRadio: false,
            isInput: false,
            isCheckbox: false,
            isDropdown: false,
            isDate: true,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Completion'
        },
        {
            id: 9,
            key: 'Employment Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Goals'
        },
        {
            id: 10,
            key: 'Task to Reach Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Tasks'
        },
        {
            id: 11,
            key: 'Progress to Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Progress'
        },
        {
            id: 12,
            key: 'Completion Date',
            value: '',
            isRadio: false,
            isInput: false,
            isCheckbox: false,
            isDropdown: false,
            isDate: true,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Completion'
        },
        {
            id: 13,
            key: 'Transportation Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Goals'
        },
        {
            id: 14,
            key: 'Task to Reach Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Tasks'
        },
        {
            id: 15,
            key: 'Progress to Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Progress'
        },
        {
            id: 16,
            key: 'Completion Date',
            value: '',
            isRadio: false,
            isInput: false,
            isCheckbox: false,
            isDropdown: false,
            isDate: true,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Completion'
        },
        {
            id: 17,
            key: 'Supportive Connections Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Goals'
        },
        {
            id: 18,
            key: 'Task to Reach Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Tasks'
        },
        {
            id: 19,
            key: 'Progress to Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Progress'
        },
        {
            id: 20,
            key: 'Completion Date',
            value: '',
            isRadio: false,
            isInput: false,
            isCheckbox: false,
            isDropdown: false,
            isDate: true,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Completion'
        },
        {
            id: 21,
            key: 'Other Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Goals'
        },
        {
            id: 22,
            key: 'Task to Reach Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Tasks'
        },
        {
            id: 23,
            key: 'Progress to Goals',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Progress'
        },
        {
            id: 24,
            key: 'Completion Date',
            value: '',
            isRadio: false,
            isInput: false,
            isCheckbox: false,
            isDropdown: false,
            isDate: true,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Completion'
        },
        {
            id: 25,
            key: 'Notes',
            value: '',
            isRadio: false,
            isInput: false,
            isTextbox: true,
            isCheckbox: false,
            isDropdown: false,
            isDate: false,
            hasDependency: false,
            hasPlaceholder: true,
            placeHolderValue: 'Notes'
        }
    ]
};