export const GET_HEALTH: any = {
    "id": 2,
    "appraisalId": 1,
    "completedBy": "Tia.Magee@mdcps.ms.gov",
    "medicalIssues": "Big toe of left foot hurts in days that end in Y.  Eyeballs twitch when I take tests.  And I have a hangnail.",
    "hasTraumaticEvent": true,
    "isVictimPhysical": true,
    "isVictimEmotional": false,
    "isVictimSexual": false,
    "isVictimNeglect": true,
    "isVictimOther": true,
    "victimOtherText": "Bullying",
    "lastDentalExam": "June 1",
    "lastMedicalExam": "June 2",
    "lastVisionExam": "June 3",
    "lastPsychExam": "June 4",
    "isSexuallyActive": true,
    "hasAdult": true,
    "hasBeenTestedHIV": true,
    "lastHIVTestDate": "June 5",
    "hivTestResults": null,
    "hasBeenTestedSTD": true,
    "lastSTDTestDate": "June 6",
    "stdTestResults": null,
    "isMentalHealth": true,
    "mentalHealthType": "Depression, Forgetfullness, Depression",
    "isSubstanceAbuse": false,
    "isLearningDisability": false,
    "isDevelopDisability": false,
    "isPhysicalDisability": true,
    "isTakingMedication": true,
    "currentMedicationText": "Asprin, Aleve, B12",
    "areMedicationsAdministered": false,
    "keepTrackOfAppointments": true,
    "concerns": [],
    "goals": [
      {
        "id": 9,
        "createDt": "09/25/2018 14:50",
        "goalText": "Run 5 min mile",
        "tasks": "Practice",
        "personResp": "Pete and Joe",
        "progress": "Looking for better running shoes",
        "completeDt": "Tomorrow"
      }
    ],
    "progress": 1
  }