export const GET_EDUCATION_INFO: any = {
    "Concerns":null,
	"Goals":[
		{
			"id":1,
			"createDt":"08\/29\/2018 16:33",
			"goalText":"Pass out more cowbells at home games",
			"tasks":"Buy more cowbells",
			"personResp":"Hugh Freeze",
			"progress":"Check has been cut",
			"completeDt":"10\/14\/2018"
		},
		{
			"id":2,
			"createDt":"08\/29\/2018 16:34",
			"goalText":"Provide more red swingline staplers at away games",
			"tasks":"Call Office Depot",
			"personResp":"Joyce Monroe",
			"progress":"TBD",
			"completeDt":"11\/02\/2018"
		}
	],
	"Progress":0,
	"id":2,
	"appraisalId":1,
	"completeDt":"\/Date(1535568369383-0500)\/",
	"commitDt":null,
	"completedBy":"Veronica.Green@mdcps.ms.gov",
	"over18HighestEd":"Some high school",
	"past90Treatment":false,
	"isCurrentlyEnrolled":true,
	"currentEnrollType":"High School",
	"pastYearSuspendExpel":false,
	"postSecondaryInfo":{
		"id":1,
		"ps_Grade":"Sophomore",
		" ps_isEnrolledETV":false,
		" ps_lastETVFundDate":null,
		" ps_sixMonthA":true,
		" ps_sixMonthB":true,
		" ps_sixMonthC":false,
		" ps_sixMonthD":false,
		" ps_sixMonthF":false,
		" ps_sixMonthNotSure":false,
		" ps_sixMonthNoneAbove":false,
		" ps_needHelpMath":false,
		" ps_needHelpEnglish":false,
		" ps_needHelpScience":true,
		" ps_needHelpHistorySS":false,
		" ps_needHelpLangArts":false,
		" ps_needHelpOther":true,
		" ps_needHelpOtherText":"Fine Arts",
		" ps_whereEnrolled":"Mississippi State Cowversity",
		" ps_enrollType":"Full Time",
		" ps_careerGoals":"More Cowbell" 
	},
	"isMiddleSchool":false,
	"isHighSchool":true,
	"isHomeSchool":false,
	"isGED":true,
	"isVocational":false,
	"isOccupationalCertificate":false,
	"isPostSecondaryEducationalProgram":true,
	"middleSchoolInfo":{
		"id":1,
		"educationId":2,
		"grade":"7",
		"hasIEPRuling":true,
		"hasBIDPlan":false,
		"credits":"14",
		"creditsNeeded":"46",
		"correctGradeForAge":true,
		"notCorrectGradeExplain":null,
		"hasGradeA":false,
		"hasGradeB":true,
		"hasGradeC":true,
		"hasGradeD":true,
		"hasGradeF":false,
		"hasGradeNotSure":false,
		"hasGradeNoneAbove":false,
		"needHelpMath":true,
		"needHelpEnglish":true,
		"needHelpScience":false,
		"needHelpHistorySS":true,
		"needHelpLanguageArts":false,
		"needHelpOther":false,
		"needHelpOtherExplain":false,
		"passedStateLevelTests":false,
		"noPassAlgebraI":true,
		"noPassBiologyI":false,
		"noPassEnglishII":true,
		"noPassUSHistory":false
	},
	"highSchoolInfo":{
		"id":1,
		"educationId":2,
		"grade":"10",
		"hasIEPRuling":true,
		"hasBIDPlan":false,
		"credits":"33",
		"creditsNeeded":null,
		"correctGradeForAge":true,
		"notCorrectGradeExplain":null,
		"hasGradeA":true,
		"hasGradeB":true,
		"hasGradeC":false,
		"hasGradeD":false,
		"hasGradeF":false,
		"hasGradeNotSure":false,
		"hasGradeNoneAbove":false,
		"needHelpMath":true,
		"needHelpEnglish":false,
		"needHelpScience":false,
		"needHelpHistorySS":true,
		"needHelpLanguageArts":false,
		"needHelpOther":false,
		"needHelpOtherExplain":null,
		"passedStateLevelTests":true,
		"noPassAlgebraI":false,
		"noPassBiologyI":false,
		"noPassEnglishII":false,
		"noPassUSHistory":false
	},
	"homeSchoolInfo":{
		"id":1,
		"educationId":2,
		"grade":"10",
		"hasIEPRuling":true,
		"hasBIDPlan":false,
		"credits":"33",
		"creditsNeeded":null,
		"correctGradeForAge":true,
		"notCorrectGradeExplain":null,
		"hasGradeA":true,
		"hasGradeB":true,
		"hasGradeC":false,
		"hasGradeD":false,
		"hasGradeF":false,
		"hasGradeNotSure":false,
		"hasGradeNoneAbove":false,
		"needHelpMath":true,
		"needHelpEnglish":false,
		"needHelpScience":false,
		"needHelpHistorySS":true,
		"needHelpLanguageArts":false,
		"needHelpOther":false,
		"needHelpOtherExplain":null,
		"passedStateLevelTests":true,
		"noPassAlgebraI":false,
		"noPassBiologyI":false,
		"noPassEnglishII":false,
		"noPassUSHistory":false
	},
	"gedInfo":{
		"id":1,
		"educationId":2,
		"progress":"Progress has been made",
		"expectedTestDate":"10\/31\/2018"
	},
	"educationPlan":{
		"id":1,
		"educationId":2,
		"planToAttend":"Two Year Program",
		"naExplain":null,
		"otherExplain":null,
		"expectedArea":"Paralegal"
	},
	"opinions":{
		"id":1,
		"educationId":2,
		"schoolIsWasteOfTime":"Disagree",
		"importantToMakeGoodGrades":"Strongly Agree",
		"educationImportantForSuccess":"Agree"
	}
}