export const INSERT_PERSONAL_INFO: any = {  
    "id":2,
    "appraisalId":1,
    "completeDt":"\/Date(1537475427330-0500)\/",
    "commitDt":null,
    "completedBy":"Taneisha.Samuels@mdcps.ms.gov",
    "isEducation":true,
    "isEmployment":false,
    "isParenting":false,
    "isMentalHealth":true,
    "isTransportation":true,
    "isMedical":true,
    "isOther":true,
    "otherText":"Braces",
    "supportLooksLike":"Dental Work",
    "oneGoalSixMonths":"To get rid of braces",
    "whatMotivatesYou":"A green magic marker",
    "currentChallenges":"The bad air quality",
    "hasTransportation":true,
    "transportationKind":"Big Wheels",
    "transportationBarriers":"No wheels on the big wheels",
    "transportationPlans":"Tricycle",
    "concerns":null,
    "goals":null,
    "progress":1
 }